config/routes.rb
Rails.application.routes.draw do
  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end
  resources :charges, only: [:new, :create]
  resources :users, only: [:edit, :update]


  post 'users/update'

  devise_for :users



  get 'about' => 'welcome#about'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/amount.rb
class Amount
  def self.default
    10_00
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :wikis, dependent: :destroy
  has_many :collaborators
  has_many :wiki_collaborations, through: :collaborators, source: :wiki

  after_initialize { self.role ||= :member }

  enum role: [:member, :premium, :admin]

  def downgrade_wikis
    self.wikis.each do |wiki|
      wiki.make_public
    end
  end
end

app/models/view.rb
class View < ApplicationRecord

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  def make_public
    update_attribute(:private, false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  include Pundit
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: 15_00,
      description: "Blocipedia Premium--#{current_user.email}",
      currency: 'usd'
    )

    if charge.paid
      current_user.premium!
      flash[:notice] = "Thank you for upgrading, #{current_user.email}! You can now create private wikis."
      redirect_to wikis_path
    end

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Blocipedia Premium - #{current_user.email}",
      amount: 15_00
      }
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def create
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.find(params[:user_id])
    @collaborator = Collaborator.new(user: @user, wiki: @wiki)

    if @collaborator.save
      flash[:notice] = "New collaborator added"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error adding the collaborator. Please try again."
      redirect_to edit_wiki_path(@wiki)
    end
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "You have successfully removed a collaborator."
      redirect_to @wiki
    else
      flash[:error] = "There was an error removing the collaborator. Please try again."
      render :show
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update
    @user = current_user
    @user.member!
    @user.downgrade_wikis


    if @user.save
      flash[:notice] = "You have been downgraded to a regular membership."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error. Please try again."
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    @collaborators = @wiki.collaborators
  end

  def new
    @wiki = Wiki.new
    @users = User.where.not(id: current_user.id)
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was saved"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.where.not(id: current_user.id)
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was updated"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error updating the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the wiki"
      render :show
    end
  end

  private
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, :user, :user_ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def user_is_authorized_to_create_private_wikis?(wiki)
    user.admin? || user.premium?
  end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
<h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About/Upgrade/Downgrade", about_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>
      <% if user_signed_in? %>
      <li class= 'pull-right'>Signed in as: <strong><%= current_user.email %></strong></li>
      <li class="pull-right"><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
      <li class='pull-right'><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
      <% else %>
      <li class='pull-right'><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %></li>
      <li class='pull-right'><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %></li>
      <% end %>
    </ul>
  </div>
  <% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
  <% elsif flash[:alert] %>
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:alert] %>
  </div>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/about.html.erb
<div class:'col-md-4'>
<% if current_user.member? %>
<%= button_to "Upgrade my account", charges_path, class: 'btn btn-success' %>
<% elsif current_user.premium? %>
  <%= button_to "Downgrade Your Account", users_update_path, method: :post, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to downgrade?'} %>
<% end %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to Blocipedia!</h1>

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>
  <div class='form-group'>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    </div>
    <div class="form-group">
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
   </div>
   <% if current_user.premium? or current_user.admin? %>
   <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki?
      <% end %>
    </div>
    <% end %>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>
<% if wiki.private? && (current_user.admin? || @wiki.user_id == current_user.id) %>
<h2>Add Collaborators</h2>
   <% @users.each do |user| %>
   <div>
   <%= link_to user.email, wiki_collaborators_path(user_id: user.id, wiki_id: wiki.id), method: :post %>
  </div>
   <% end %>
 <%end%>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
<div class='row'>
  <div class= 'col-md-4'>
    <p>Please keep our wikis factual!!!</p>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: {wiki: @wiki} %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>Wikis</h2>

  <div class="row">
    <div class="col-md-8">
      <h2> Wikis </h4>
        <% @wikis.each do |wiki| %>
        <h4> <%= link_to wiki.title, wiki %> </h4>
        <%end %>
        </div>
        <% if policy(Wiki).create? %>
        <div class='col-md-4'>
          <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
        </div>
        <% end %>
      </div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
<div class='row'>
  <div class= 'col-md-4'>
    <p>Please keep our wikis factual!!!</p>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: {wiki: @wiki} %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1>
  <%= @wiki.title %> <br>
</h1>

<div class ="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
  <div class='col-md-4'>
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <% if policy(@wiki).destroy? %>
    <%= link_to "Delete Post", [@wiki], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
    <% end %>
  </div>
</div>
<% if @collaborators.size > 0 %>
<h3>
  Collaborators for this wiki
</h3>
<div class="row>">
<% @collaborators.each do |collaborator| %>
<div class'col-md-4'>
  <%= User.find_by_id(collaborator.user_id).email %>
  <% if (current_user.admin? || @wiki.user_id == current_user.id) %>
  <%= link_to "Remove Collaborator", wiki_collaborator_path(@wiki, collaborator.id), method: :delete, data: {confirm: 'Are you sure you want to remove this collaborator?'} %>
  <% end %>
</div>
<% end %>
</div>
<% end %>